project:
  type: website
  output-dir: docs

website:
  title: "Michael Torrisi's ePortfolio"
  navbar:
    left:
      - href: Portfolio-Main.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: project.qmd
        text: "International Math Olympiad Project"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual