---
title: "About Me"
format: html
---

Michael is a Hard-working, driven student researcher with 4+ years of research experience and excellent academic performance. Confident speaker, proficient with R. He is eager to discover more about the ecosystems of our world and the interactions that drive them. He is interested in expanding these skills and applying them to his current research with Dr. Salvador Jorgensen, Ph.D. about understanding white shark ontogeny and prey interaction along the central California coast.

## Education

California State University, Monterey Bay \| Seaside, CA\
B.S., Marine Science \| 2022 - 2026

## Experience

Project Shark Scar \| Undergraduate Data Analyst \| February 2023 - August 2026

## Research Disseminations

**Torrisi, M.**, Walter, A., Yee, K., Anderson, S.D., Jorgensen, S. “An Examination of the Ontogenetic Shift of White Shark Prey Preference from Fishes to Pinniped Marine Mammals” presented at the Research, Scholarship, & Creative Activity Spring Showcase at CSUMB. April 2024, Seaside, California.

**Torrisi, M.**, Walter, A., Yee, K., Anderson, Andrzejaczek, S., Block, B.A., Chapple, T.K., DiGiacomo, A., Kanive, P.E., Jorgensen, S. “An Examination of the Ontogenetic Shift of White Shark Prey Preference from Fishes to Pinniped Marine Mammals” presented at the Western Society of the Naturalists Research Conference. November 2024, Portland, Oregon.

**Torrisi, M.**, Walter, A., Yee, K., Jorgensen, S. “When Dinner Fights Back: Inferring White Shark Behavioral Adaptations from Prey Handling Injuries” presented at the Research, Scholarship, & Creative Activity Spring Showcase at CSUMB. April 2025, Seaside, California.

**Torrisi, M.**, Walter, A., Yee, K., Jorgensen, S. “When Dinner Fights Back: Inferring White Shark Behavioral Adaptations from Prey Handling Injuries” presented at the Summer Research Symposium at CSUMB. August 2025, Seaside, California.

**Torrisi, M.**, Walter, A., Yee, K., Anderson, Andrzejaczek, S., Block, B.A., Chapple, T.K., DiGiacomo, A., Kanive, P.E., Jorgensen, S. “When Dinner Fights Back: Inferring White Shark Behavioral Adaptations from Prey Handling Injuries” presented at the Western Society of the Naturalists Research Conference. November 2025, San Diego, California.

**Torrisi, M.**, Walter, A., Yee, K., Anderson, Andrzejaczek, S., Block, B.A., Chapple, T.K., DiGiacomo, A., Kanive, P.E., Jorgensen, S. “Prey Handling Scars Incurred by White Sharks Reveal Size and Sex-Based Differences in Foraging Patterns” presented at the Northeast Pacific Shark Symposium Research Conference. March 2026, Newport, Oregon.

**Torrisi, M.**, Walter, A., Yee, K., Anderson, Andrzejaczek, S., Block, B.A., Chapple, T.K., DiGiacomo, A., Kanive, P.E., Jorgensen, S. “Prey Handling Scars Incurred by White Sharks Reveal Size and Sex-Based Differences in Foraging Patterns” presented at the Research, Scholarship, & Creative Activity Spring Showcase at CSUMB. April 2026, Seaside, California.

**Torrisi, M.**, Walter, A., Yee, K., Anderson, S. D., Andrzejaczek, S., Block, B. A., et al. (In Progress). Prey Handling Scars Incurred by White Sharks Reveal Size and Sex-Based Differences in Foraging Patterns. Front. Mar. Sci. (In Progress)


## Honors and Awards

CSU COAST & Jim and Peggy Ryan Marine Science Undergraduate Research Award Recipient (Spring 2025, Spring 2026)

Undergraduate Research Opportunities Center (UROC) Researcher (Spring 2025 - Summer 2026)

CSUMB Dean’s List (Fall 2022 - Spring 2026)

