---
title: "Portfolio Project"
about:
  template: jolla
format: html
execute: 
  echo: false
  warning: false
  message: false
embed-resources: true
---


# Portfolio Project

```{r}
#| label: setup
#| include: false
library(tidyverse)
library(purrr)
```
## Data Description



## Data Cleaning


```{r}
IMO_data <- read_csv("project-files/data-raw/individual_results_df.csv")
country_continents <- read_csv("project-files/data-raw/list-of-countries-by-continent-2025.csv")
```

```{r}
IMO_alltime_gold <- IMO_data %>% 
  mutate(award = substring(award, 1, 4),
         name_lenth = str_length(country)) %>% 
  filter(award == "Gold" | award == "Bron" | award == "Silv") %>% 
  filter(name_lenth > 3) %>% 
  mutate(award = case_when(award == "Gold" ~ "Gold",
                           award == "Silv" ~ "Silver",
                           award == "Bron" ~ "Bronze")) %>% 
  select(year, country, award) %>% 
  group_by(country) %>% 
  summarise(alltime_gold = n(), .groups = "drop") %>% 
  arrange(desc(alltime_gold))
```


```{r}
IMO_21stcentury_gold <- IMO_data %>% 
  filter(year >= 2000) %>% 
  mutate(award = substring(award, 1, 4),
         name_lenth = str_length(country)) %>% 
  filter(award == "Gold" | award == "Bron" | award == "Silv") %>% 
  filter(name_lenth > 3) %>% 
  mutate(award = case_when(award == "Gold" ~ "Gold",
                           award == "Silv" ~ "Silver",
                           award == "Bron" ~ "Bronze")) %>% 
  select(year, country, award) %>% 
  group_by(country) %>% 
  summarise(century21_gold = n()) %>% 
  arrange(desc(century21_gold))
```

```{r}
IMO_20thcentury_gold <- IMO_data %>% 
  filter(year < 2000) %>% 
  mutate(award = substring(award, 1, 4),
         name_lenth = str_length(country)) %>% 
  filter(award == "Gold" | award == "Bron" | award == "Silv") %>% 
  filter(name_lenth > 3) %>% 
  mutate(award = case_when(award == "Gold" ~ "Gold",
                           award == "Silv" ~ "Silver",
                           award == "Bron" ~ "Bronze")) %>% 
  select(year, country, award) %>% 
  group_by(country) %>% 
  summarise(century20_gold = n()) %>% 
  arrange(desc(century20_gold))
```

```{r}
IMO_gold_counts <- IMO_alltime_gold %>% 
  full_join(IMO_20thcentury_gold, by = "country") %>% 
  full_join(IMO_21stcentury_gold, by = "country") %>% 
  mutate_if(is.integer, ~replace(., is.na(.), 0))
```

```{r}
write_csv(IMO_gold_counts, "project-files/data-clean/IMO_gold_counts.csv")
```

## Visualization 1
```{r}
IMO_data %>% 
  select(p1, p2, p3, p4, p5, p6, p7, year) %>% 
  group_by(year) %>% 
  summarise(p1 = mean(p1, na.rm = TRUE),
            p2 = mean(p2, na.rm = TRUE),
            p3 = mean(p3, na.rm = TRUE),
            p4 = mean(p4, na.rm = TRUE),
            p5 = mean(p5, na.rm = TRUE),
            p6 = mean(p6, na.rm = TRUE)) %>% 
  pivot_longer(cols = 2:7, names_to = "problem_num", values_to = "mean_score") %>% 
  ggplot(aes(x = year, y = mean_score)) + 
  geom_line() +
  facet_grid(rows = vars(problem_num)) +
  labs(x = "Year",
       y = "Mean Score") +
  theme_light()
```

## Visualization 2
```{r}
IMO_data %>% 
  left_join(country_continents, by = "country") %>% 
  mutate(continent = case_when(country == "People's Republic of China" ~ "Asia",
                               country == "United States of America" ~ "North America",
                               country == "Republic of Korea" ~ "Asia",
                               country == "Türkiye" ~ "Asia",
                               country == "Islamic Republic of Iran" ~ "Asia",
                               country == "Republic of Moldova" ~ "Europe",
                               country == "Kosovo" ~ "Europe",
                               country == "Russian Federation" ~ "Asia",
                               country == "Democratic People's Republic of Korea" ~ "Asia",
                               country == "Serbia and Montenegro" ~ "Europe",
                               country == "Yugoslavia" ~ "Europe",
                               country == "Turkish Republic of Northern Cyprus" ~ "Asia",
                               country == "Yugoslavia" ~ "Europe",
                               country == "Czechoslovakia" ~ "Europe",
                               country == "Union of Soviet Socialist Republics" ~ "Asia",
                               country == "German Democratic Republic" ~ "Asia",
                               continent == "Oceania" ~ "Australia",
                              TRUE ~ continent)) %>% 
  filter(!is.na(continent)) %>% 
  select(p1, p2, p3, p4, p5, p6, p7, year, continent) %>% 
  group_by(continent, year) %>% 
  summarise(p1 = mean(p1, na.rm = TRUE),
            p2 = mean(p2, na.rm = TRUE),
            p3 = mean(p3, na.rm = TRUE),
            p4 = mean(p4, na.rm = TRUE),
            p5 = mean(p5, na.rm = TRUE),
            p6 = mean(p6, na.rm = TRUE)) %>% 
  pivot_longer(cols = 3:8, names_to = "problem_num", values_to = "mean_score") %>% 
  mutate(mean_score = case_when(mean_score == "NaN" ~ NA,
                                TRUE ~ mean_score)) %>% 
  filter(continent != "Oceania") %>% 
  ggplot(aes(x = year, y = mean_score)) + 
  geom_line() +
  facet_grid(rows = vars(problem_num), cols = vars(continent)) +
  labs(x = "Year",
       y = "Mean Score") +
  theme_light()
  
```


